image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name DistriLock --icon icon.png --product-name DistriLock --product-version "1.2.3" --copyright "Copyright (c) 2023 Valentin Draganescu"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a DistriLock-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: DistriLock-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf DistriLock-macos.tar.gz -C dist DistriLock.app

  artifacts:
  - path: DistriLock-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf DistriLock-linux.tar.gz -C dist DistriLock

  artifacts:
  - path: DistriLock-linux.tar.gz